Updates to Read me
wlfmnstr/the-heartbroken-dev-tier-1 pull request #2
Opened 2024-04-11 20:05 UTC by Kazleigh

I have used the default settings from the pull request for the base and head repository so I hope this works - but should be updating the read me - Added imagery for terminal, command prompt and downloads section of git at 400px. Added short description of Git Bash, added 'following default settings' to git download description.

2024-04-12 00:36 UTC, wlfmnstr commented on README.md
> +        - Git Bash is the name for the command-line terminal environment
This is a great point to add!

2024-04-12 00:37 UTC, wlfmnstr commented on README.md
> +1. Coming soon....
A very important additional `.`

2024-04-12 00:41 UTC, wlfmnstr requested changes
@Kazleigh Look good to me and thanks for the contribution! Only request is to delete the duplicate index.html at /student-resumes/index.html

2024-04-12 00:41 UTC, wlfmnstr commented on student-resumes/index.html
I think you can delete this file.

2024-04-12 08:20 UTC, Kazleigh commented on student-resumes/index.html
I have deleted it out and committed the change - so this should now be resolved

2024-04-12 08:26 UTC, Kazleigh commented
The requested change has been complete as I deleted the extra file out and committed it - but it is still showing change requested and merging blocked and I am unsure how to resolve further or if requires your input? Sorry to be a pain!

2024-04-13 22:51 UTC, wlfmnstr approved these changes
lgtm! Thanks!

2024-04-13 22:52 UTC, merged